// src/components/HotsnackDetailModal.tsx
"use client";

import { useState } from "react";
import type { Hotsnack } from "@/db/schema";
import PictureFrame from "./PictureFrame";
import AnimatedNumber from "./AnimatedNumber";
import Divider from "./Divider";

interface HotsnackDetailModalProps {
  isVisible: boolean;
  hotsnack: Hotsnack | null;
  onClose: () => void;
}

function getStoreYear(store: string): string {
  if (store === "セブン-イレブン") return "1974年 - 現在";
  if (store === "LAWSON") return "1975年 - 現在";
  if (store === "FamilyMart") return "1973年 - 現在";
  return "";
}

export default function HotsnackDetailModal({
  isVisible,
  hotsnack,
  onClose,
}: HotsnackDetailModalProps) {
  const [show, setShow] = useState(true);
  const [likeCount, setLikeCount] = useState(0);
  const [dislikeCount, setDislikeCount] = useState(0);
  const [speechDisabled, setSpeechDisabled] = useState(false);

  // Sync counts when hotsnack changes
  const displayLike = hotsnack ? hotsnack.like_count + likeCount : 0;
  const displayDislike = hotsnack ? hotsnack.dislike_count + dislikeCount : 0;
  const evaluationAmount = hotsnack ? hotsnack.price * displayLike : 0;

  if (!isVisible || !hotsnack) return null;

  const addLike = async () => {
    const res = await fetch(`/api/v1/hotsnack/${hotsnack.item_uuid}/like`, {
      method: "PUT",
    });
    if (res.ok) {
      setLikeCount((c) => c + 1);
    }
  };

  const addDislike = async () => {
    const res = await fetch(`/api/v1/hotsnack/${hotsnack.item_uuid}/dislike`, {
      method: "PUT",
    });
    if (res.ok) {
      setDislikeCount((c) => c + 1);
    }
  };

  const speak = () => {
    setSpeechDisabled(true);
    const utterance = new SpeechSynthesisUtterance(hotsnack.description);
    speechSynthesis.speak(utterance);
    setTimeout(() => setSpeechDisabled(false), 3000);
  };

  const handleClose = () => {
    setLikeCount(0);
    setDislikeCount(0);
    onClose();
  };

  return (
    <div
      className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"
      onClick={handleClose}
    >
      <div
        className="bg-[#f6f5ee] rounded-lg max-w-[375px] w-full max-h-[90vh] overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Evaluation & Like/Dislike */}
        <div className="grid grid-cols-3 gap-1 mt-4 mb-2 mx-12">
          <div className="col-span-1 text-center">
            <div className="text-base font-bold">評価額</div>
          </div>
          <div className="text-center">
            <button onClick={addLike} className="p-1">
              👍
            </button>
          </div>
          <div className="text-center">
            <button onClick={addDislike} className="p-1">
              👎
            </button>
          </div>
          <div className="col-span-1 text-center text-sm">
            <AnimatedNumber value={evaluationAmount} /> 円
          </div>
          <div className="text-center text-sm">{displayLike}</div>
          <div className="text-center text-sm">{displayDislike}</div>
        </div>

        <div className="mx-4">
          <Divider />
        </div>

        {/* Picture */}
        <div className="mx-10 my-8">
          <PictureFrame>

            <img
              src={hotsnack.image}
              alt={hotsnack.name}
              className="w-full h-auto"
            />
          </PictureFrame>
        </div>

        {/* Name plate */}
        <div className="mx-16 my-4 shadow-lg">
          <div className="text-center text-xs font-bold pt-2 pb-0 whitespace-pre-line text-[#2c281e]">
            {hotsnack.name}
          </div>
          <div className="text-center text-[0.55em] font-light pt-1 pb-2 text-[#2c281e]">
            {hotsnack.price}円（税込）
          </div>
          <hr className="hr-plate" />
          <div className="text-center text-xs font-bold pt-2 pb-0 font-[family-name:var(--font-lusitana)] text-[#2c281e]">
            {hotsnack.store}
          </div>
          <div className="text-center text-[0.55em] font-light pt-1 pb-0 text-[#2c281e]">
            {getStoreYear(hotsnack.store)}
          </div>
          <div className="text-center text-[0.55em] font-light pt-0 pb-2 text-[#2c281e]">
            {hotsnack.genre} / {hotsnack.ingredient}
          </div>
        </div>

        {/* Description */}
        <div className="mx-8 mb-2">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-1">
              <span className="text-sm">作品解説</span>
              <button
                onClick={speak}
                disabled={speechDisabled}
                className="p-1 disabled:opacity-50"
              >
                🔊
              </button>
            </div>
            <button onClick={() => setShow(!show)} className="p-1 text-lg">
              {show ? "▲" : "▼"}
            </button>
          </div>
          {show && (
            <div>
              <Divider />
              <p className="text-sm text-gray-700 py-2">
                {hotsnack.description}
              </p>
            </div>
          )}
        </div>

        <div className="text-center mb-4">
          <button
            onClick={handleClose}
            className="px-6 py-2 bg-gray-200 rounded hover:bg-gray-300"
          >
            閉じる
          </button>
        </div>
      </div>
    </div>
  );
}

// app/javascript/components/hotsnackmodal/HotsnackDetailModal.vue
<template>
    <v-dialog v-model="isVisible" max-width="375" scrollable @click:outside="hundleCloseHotsnackDetailModal">
        <v-card class="mx-auto overflow-auto" max-width="375" color="#f6f5ee" outlined v-if="hotsnack">
            <v-row justify="center" align="center" class="mt-4 mb-2 mx-12">
                <v-col cols="6" class="pa-0">
                    <v-card outlined color="#f6f5ee">
                        <div class="text-center">
                            <v-btn text class="text-h6">評価額</v-btn>
                        </div>
                    </v-card>
                </v-col>
                <v-col class="pa-0">
                    <v-card outlined color="#f6f5ee">
                        <div class="text-center">
                            <v-btn icon @click="addLikeCount">
                                <v-icon icon>mdi-thumb-up</v-icon>
                            </v-btn>
                        </div>
                    </v-card>
                </v-col>
                <v-col class="pa-0">
                    <v-card outlined color="#f6f5ee">
                        <div class="text-center">
                            <v-btn icon @click="addDislikeCount">
                                <v-icon icon>mdi-thumb-down</v-icon>
                            </v-btn>
                        </div>
                    </v-card>
                </v-col>
                <v-col cols="6" class="pa-0">
                    <v-card outlined color="#f6f5ee">
                        <div class="text-center"><animated-number :value="multiplyLikeCountAndPrice" />円</div>
                    </v-card>
                </v-col>
                <v-col class="pa-0">
                    <v-card outlined color="#f6f5ee">
                        <div class="text-center">{{ hotsnack.like_count }}</div>
                    </v-card>
                </v-col>
                <v-col class="pa-0">
                    <v-card outlined color="#f6f5ee">
                        <div class="text-center">{{ hotsnack.dislike_count }}</div>
                    </v-card>
                </v-col>
            </v-row>

            <v-row class="mx-4"><base-divider /></v-row>

            <v-card class="mx-10 my-8" color="#f6f5ee" outlined>
                <v-container class="outline">
                    <v-container class="inline">
                        <v-container class="block">
                            <v-container class="border">
                                <v-img :src="hotsnack.image" />
                            </v-container>
                        </v-container>
                    </v-container>
                </v-container>
            </v-card>

            <v-card raised elevation="8" tile class="mx-16 my-4">
                <v-col align="center" class="s-font pt-2 pb-0 msg-wrapper">{{ hotsnack.name }}</v-col>
                <v-col align="center" class="xs-font pt-1 pb-2">{{ hotsnack.price }}円（税込）</v-col>
                <hr class="hr2" />
                <v-col align="center" class="s-font pt-2 pb-0 Lusitana">{{ hotsnack.store }}</v-col>
                <v-col align="center" class="xs-font pt-1 pb-0" v-if="hotsnack.store === 'セブン-イレブン'"
                    >1974年 - 現在</v-col
                >
                <v-col align="center" class="xs-font pt-1 pb-0" v-else-if="hotsnack.store === 'LAWSON'"
                    >1975年 - 現在</v-col
                >
                <v-col align="center" class="xs-font pt-1 pb-0" v-else-if="hotsnack.store === 'FamilyMart'"
                    >1973年 - 現在</v-col
                >
                <v-col align="center" class="xs-font pt-0 pb-2">{{ hotsnackCategoryDetail }}</v-col>
            </v-card>

            <v-card class="mx-8" color="#f6f5ee" outlined>
                <v-card-actions>
                    <v-col>
                        作品解説
                        <v-btn icon @click="onSpeakHotsnackDescription" :disabled="disabledDescriptionButton">
                            <v-icon icon>mdi-volume-high</v-icon>
                        </v-btn>
                    </v-col>
                    <v-spacer></v-spacer>
                    <v-btn icon @click="show = !show">
                        <v-icon>{{ show ? 'mdi-chevron-up' : 'mdi-chevron-down' }}</v-icon>
                    </v-btn>
                </v-card-actions>

                <v-expand-transition>
                    <div v-show="show">
                        <base-divider />
                        <v-card-text>{{ hotsnack.description }}</v-card-text>
                    </div>
                </v-expand-transition>
            </v-card>
            <v-col align="center" class="mb-4">
                <v-btn @click="hundleCloseHotsnackDetailModal">閉じる</v-btn>
            </v-col>
        </v-card>
    </v-dialog>
</template>

<script>
import { BaseDivider } from '../atom/dividers/index'
import { AnimatedNumber } from '../atom/numbers/index'

export default {
    components: {
        BaseDivider,
        AnimatedNumber,
    },
    props: {
        hotsnack: {
            type: Object,
            required: true,
        },
        isVisible: {
            type: Boolean,
            required: true,
            default: false,
        },
    },
    data() {
        return {
            show: true,
            voices: [],
            disabledDescriptionButton: false,
        }
    },
    computed: {
        multiplyLikeCountAndPrice() {
            if (!this.hotsnack || !this.hotsnack.price || !this.hotsnack.like_count) {
                return 0
            }

            return this.hotsnack.price * this.hotsnack.like_count
        },
        hotsnackCategoryDetail() {
            return this.hotsnack.genre + ' / ' + this.hotsnack.ingredient
        },
    },
    methods: {
        hundleCloseHotsnackDetailModal() {
            this.$emit('close-hotsnack-detail-modal')
        },
        addLikeCount() {
            const id = this.hotsnack.item_uuid
            this.$axios
                .put(`/hotsnack/${id}/like`)
                .then((res) => {
                    if (res.status === 200) {
                        this.hotsnack.like_count++
                    }
                })
                .catch((error) => console.log(error))
        },
        addDislikeCount() {
            const id = this.hotsnack.item_uuid
            this.$axios
                .put(`/hotsnack/${id}/dislike`)
                .then((res) => {
                    if (res.status === 200) {
                        this.hotsnack.dislike_count++
                    }
                })
                .catch((error) => console.log(error))
        },
        onSpeakHotsnackDescription() {
            this.disabledDescriptionButton = true
            const utterance = new SpeechSynthesisUtterance(this.hotsnack.description)
            utterance.voice = this.$data.voices[0]
            speechSynthesis.speak(utterance)
            setTimeout(() => (this.disabledDescriptionButton = false), 3000)
        },
    },
}
</script>

<style scoped>
.border {
    background: #fff;
    display: block;
    width: 88%;
    height: auto;
    padding: 6%;
    box-shadow: inset 0px 0.3em 0.1em rgba(0, 0, 0, 0.2);
}
.block {
    display: block;
}
.inline {
    background-color: #f8f8f8;
    z-index: -1;
    box-shadow: inset 0px 10px 0.5em rgba(0, 0, 0, 0.25), inset 0.1em 0px 0.1em rgba(0, 0, 0, 0.1),
        inset -0.1em 0px 0.1em rgba(0, 0, 0, 0.05), 0 0.3em 0.2em #fff;
    background-image: -moz-radial-gradient(50% 50%, circle farthest-corner, #ffffff, #f8f8f8 100%);
    background-image: -webkit-radial-gradient(50% 50%, circle farthest-corner, #ffffff, #f8f8f8 100%);
    background-image: -o-radial-gradient(50% 50%, circle farthest-corner, #ffffff, #f8f8f8 100%);
    background-image: -ms-radial-gradient(50% 50%, circle farthest-corner, #ffffff, #f8f8f8 100%);
    background-image: radial-gradient(50% 50%, circle farthest-corner, #ffffff, #f8f8f8 100%);
}
.outline {
    width: 100%;
    height: 100%;
    background: #f8f8f8;
    z-index: -2;
    box-shadow: 0px 1em 2em -1em rgba(0, 0, 0, 0.4), 0px 2em 2em -1em rgba(0, 0, 0, 0.03),
        0px 3em 2em -1em rgba(0, 0, 0, 0.2), 0px 4em 1.5em -1em rgba(0, 0, 0, 0.15),
        0px 2em 4em 0.5em rgba(0, 0, 0, 0.1), inset 0 0.2em 0.1em #fff;
}
.hr2 {
    border: none;
    width: 90%;
    height: 50px;
    border-bottom: 1px solid #1f1209;
    margin: -50px auto 0px;
}
.s-font {
    font-size: 0.75em;
    font-weight: bold;
    line-height: 1;
    color: #2c281e;
}
.Lusitana {
    font-family: 'Lusitana', cursive;
}
.xs-font {
    font-size: 0.55em;
    font-weight: lighter;
    line-height: 1.5;
    color: #2c281e;
}
.msg-wrapper {
    white-space: pre-line;
}
</style>
